// loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';

// app init
export const APP_UPDATE_LAST_SYNCED = 'APP_UPDATE_LAST_SYNCED';

// dashboard loaders
export const DASHBOARD_ENABLE_LOADER = 'DASHBOARD_ENABLE_LOADER';
export const DASHBOARD_DISABLE_LOADER = 'DASHBOARD_DISABLE_LOADER';

// dashboard
export const DASHBOARD_DATA_REQUEST = 'DASHBOARD_DATA_REQUEST';
export const DASHBOARD_DATA_RESPONSE = 'DASHBOARD_DATA_RESPONSE';
export const DASHBOARD_DATA_FAILED = 'DASHBOARD_DATA_FAILED';

// inspections loaders
export const INSPECTIONS_ENABLE_LOADER = 'INSPECTIONS_ENABLE_LOADER';
export const INSPECTIONS_DISABLE_LOADER = 'INSPECTIONS_DISABLE_LOADER';

// inspections
export const INSPECTIONS_DATA_REQUEST = 'INSPECTIONS_DATA_REQUEST';
export const INSPECTIONS_DATA_RESPONSE = 'INSPECTIONS_DATA_RESPONSE';
export const INSPECTIONS_DATA_FAILED = 'INSPECTIONS_DATA_FAILED';
export const INSPECTIONS_REMOVE_BY_ID = 'INSPECTIONS_REMOVE_BY_ID';
export const FETCH_INSPECTIONS = 'FETCH_INSPECTIONS';
export const SAVE_NEW_FETCHED_INSPECTIONS = 'SAVE_NEW_FETCHED_INSPECTIONS';
// field report

export const SAVE_SELFIE = 'SAVE_SELFIE';
export const MARK_ENTRY = 'MARK_ENTRY';
export const MARK_EXIT = 'MARK_EXIT';
export const SAVE_FIELD_DATA = 'SAVE_FIELD_DATA';
export const MAKE_SOS_REQUEST = 'MAKE_SOS_REQUEST';
export const SAVE_LOCAL_FIELD = 'SAVE_LOCAL_FIELD';
export const SUBMIT_TO_SERVER = 'SUBMIT_TO_SERVER';
export const FIELD_REPORT_REMOVE_BY_ID = 'FIELD_REPORT_REMOVE_BY_ID';
export const SERVER_REPORT_REMOVE_BY_ID = 'SERVER_REPORT_REMOVE_BY_ID';
export const SUBMIT_PENDING_AXIOS_REQUEST = 'SUBMIT_PENDING_AXIOS_REQUEST';
